using System.IO;
using System.Web;

namespace StkLib.Web
{
    public class CPage
    {

        /// <summary>
        /// For Get Page Name Ex , "Hello.aspx"
        /// </summary>
        /// <returns></returns>
        public string GetCurrentPageName()
        {
            var path = HttpContext.Current.Request.Url.AbsolutePath;
            var info = new FileInfo(path);
            var pageName = info.Name;
            return pageName;
        }
    }
}










//INSERT INTO MPO_FISH(FISH_ID)VALUES('I0');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I7'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('K0'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('K5'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('G');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I9');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('K04');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('K72');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I82');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I83');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I84');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I85');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I89');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I3');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('K9');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('H0');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('HI04');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I54');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('E12');
//INSERT INTO MPO_FISH(FISH_ID)VALUES('ESO'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('E03'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('E22'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('E9'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('TW'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('TWD'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I0'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I7'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('K0'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('G พิเศษ'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I82'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I83 พิเศษ'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I32'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('I33 พิเศษ'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('H0 พิเศษ'); 
//INSERT INTO MPO_FISH(FISH_ID)VALUES('E22 ใต้แทงก์'); 
